// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkbmnersobxehuerkfxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrYm1uZXJzb2J4ZWh1ZXJrZnh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MzkxMTgsImV4cCI6MjA3MjAxNTExOH0.7Zl4TDwWwVIW2DtwfhwGcpFggMCAffobSR_7Ah2Uwbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});